### ISSUE TITLE
Blocking analysis stops people joining a game

### ISSUE THREAD

**Issue by zabouth** [ksassnowski/utgars-chronicles.app#15]
Fathom Analytics is blocked by most adblockers by default, including uBlock Origin. This caused issues when a new user try's to join the the using the invitation link. 

![image](https://user-images.githubusercontent.com/127714/115247020-b2787500-a126-11eb-9806-d38556400ae1.png)

**Comment by ksassnowski** [comment]
Hey, thanks for pointing that out. Does it stop the redirect from happening? Weird that I've never encountered this so far

**Comment by zabouth** [comment]
Yea. I did not check if the form data is posed but the redirect does not happen.

**Comment by ksassnowski** [comment]
Alright, thanks for letting me know. This should be a fairly straight-forward fix. I think I'll be able to fix this tonight.

**Comment by ksassnowski** [comment]
This is fixed in the latest release (193ac409007e2447ce95a557d051f94db54b2699)
