### ISSUE TITLE
Problem with reverse proxy : 403 Invalid signature in invitation links

### ISSUE THREAD

**Issue by wushepeng** [ksassnowski/utgars-chronicles.app#18]
Hello
I installed the app for testing on a fresh created debian bullseye VM. It works fine when using th IP address to contact the server.
But when I configure a reverse proxy I had to do this steps (find in laravel doc) :
1. activate module by running : php artisan vendor:publish --provider="Fideloper\Proxy\TrustedProxyServiceProvider"
2. add in routes/web.php : 
$proxy_url = getenv('PROXY_URL');
$proxy_schema = getenv('PROXY_SCHEMA');
if (!empty($proxy_url)) {
        URL::forceRootUrl($proxy_url);
}
if (!empty($proxy_schema)) {
        URL::forceScheme($proxy_schema);
}
3. add the PROXY_URL and PROXY_SCHEMA in .env

But now the invitation links doesn't work. Even after a complete re-installation procedure.
I always have  "403 Invalid signature" error, even if connected by the owner account

**Comment by wushepeng** [comment]
I found a workaround

putting $url = str_replace("http://","https://", $url); in hasCorrectSignature method in vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php solve the problem, but it's not a solution.

I think the problem is incomplete installation procedure, and laravel is hard to enter in

**Comment by wushepeng** [comment]
Configuring with a web server directly in https without using "php artisan serve" solve the problem

**Comment by athshean** [comment]
> I found a workaround
> 
> putting $url = str_replace("http://","https://", $url); in hasCorrectSignature method in vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php solve the problem, but it's not a solution.
> 
> I think the problem is incomplete installation procedure, and laravel is hard to enter in

I tried this and it started giving me 500 Server Errors.
