### ISSUE TITLE
Players's name aren't displayed in the same order  

### ISSUE THREAD

**Issue by martinmestres** [ksassnowski/utgars-chronicles.app#7]
Players's name aren't displayed in the same order from a computer to another making the list unusable for turn order.

**Comment by ksassnowski** [comment]
Thanks for opening this issue! 

This should be fixed with the latest release (2ed527a96e2dd32eb3c958cf7a01efa4b35ef3d3). The player list is now always sorted alphabetically. I don't think it matters _how_ exactly they are ordered, just that they are always ordered the same way.
